/*
 * AI Generated Solution for Cramer's Rule with POSIX Threads
 * Generated by: Large Language Model
 * Date: 2026-03-09
 *
 * Description:
 * Solves a large system of linear equations (N >= 1000) using Cramer's Rule.
 * Uses pthreads for shared-memory parallelization.
 * Implements a thread-safe logger with mutexes to record execution to a file.
 * Auto-detects CPU cores using lscpu.
 */

#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <math.h>
#include <time.h>
#include <stdarg.h>

// --- Global Logger Setup ---
FILE *log_fp = NULL;
pthread_mutex_t log_mutex = PTHREAD_MUTEX_INITIALIZER;

void log_msg(const char *format, ...) {
    if (!log_fp) return;
    
    time_t now = time(NULL);
    struct tm *t = localtime(&now);
    char time_str[20];
    strftime(time_str, sizeof(time_str), "%H:%M:%S", t);

    pthread_mutex_lock(&log_mutex);
    
    // Write to file
    fprintf(log_fp, "[%s] ", time_str);
    va_list args;
    va_start(args, format);
    vfprintf(log_fp, format, args);
    va_end(args);
    fflush(log_fp);

    // Write to terminal
    printf("[%s] ", time_str);
    va_start(args, format);
    vprintf(format, args);
    va_end(args);
    
    pthread_mutex_unlock(&log_mutex);
}

// --- Matrix Structures & Math ---
typedef struct {
    int size;
    double **data;
} Matrix;

Matrix* create_matrix(int n) {
    Matrix *m = (Matrix*)malloc(sizeof(Matrix));
    m->size = n;
    m->data = (double**)malloc(n * sizeof(double*));
    for (int i = 0; i < n; i++) m->data[i] = (double*)malloc(n * sizeof(double));
    return m;
}

void free_matrix(Matrix *m) {
    for (int i = 0; i < m->size; i++) free(m->data[i]);
    free(m->data);
    free(m);
}

Matrix* copy_matrix(Matrix *src) {
    Matrix *dest = create_matrix(src->size);
    for (int i = 0; i < src->size; i++) {
        for (int j = 0; j < src->size; j++) dest->data[i][j] = src->data[i][j];
    }
    return dest;
}

void replace_column(Matrix *m, double *vec, int col) {
    for (int i = 0; i < m->size; i++) m->data[i][col] = vec[i];
}

double fast_determinant(Matrix *m) {
    Matrix *temp = copy_matrix(m);
    int n = temp->size;
    double det = 1.0;

    for (int i = 0; i < n; i++) {
        int pivot = i;
        while (pivot < n && fabs(temp->data[pivot][i]) < 1e-9) pivot++;
        if (pivot == n) { free_matrix(temp); return 0.0; }
        
        if (pivot != i) {
            double *swap = temp->data[i];
            temp->data[i] = temp->data[pivot];
            temp->data[pivot] = swap;
            det = -det;
        }
        
        det *= temp->data[i][i];
        for (int j = i + 1; j < n; j++) {
            double factor = temp->data[j][i] / temp->data[i][i];
            for (int k = i; k < n; k++) temp->data[j][k] -= factor * temp->data[i][k];
        }
    }
    free_matrix(temp);
    return det;
}

// --- Threading Setup ---
typedef struct {
    int start_col;
    int end_col;
    Matrix *A;
    double *B;
    double det_A;
    double *solutions;
    int thread_id;
} ThreadArgs;

void* worker_routine(void* arg) {
    ThreadArgs *args = (ThreadArgs*)arg;
    log_msg("Thread %d starting: columns %d to %d\n", args->thread_id, args->start_col, args->end_col - 1);

    for (int i = args->start_col; i < args->end_col; i++) {
        Matrix *local_A = copy_matrix(args->A);
        replace_column(local_A, args->B, i);
        double det_Ai = fast_determinant(local_A);
        args->solutions[i] = det_Ai / args->det_A;
        free_matrix(local_A);

        if ((i + 1) % 50 == 0 || i == args->end_col - 1) {
            log_msg("Thread %d finished up to column %d\n", args->thread_id, i);
        }
    }
    log_msg("Thread %d exiting.\n", args->thread_id);
    pthread_exit(NULL);
}

int get_cores() {
    FILE *fp = popen("lscpu | grep '^CPU(s):' | awk '{print $2}'", "r");
    if (!fp) return 1;
    int c = 1;
    if (fscanf(fp, "%d", &c) != 1) c = 1;
    pclose(fp);
    return c > 0 ? c : 1;
}

int main(int argc, char *argv[]) {
    log_fp = fopen("ai_execution_log.txt", "w");
    if (!log_fp) {
        printf("Failed to open log file.\n");
        return 1;
    }

    int N = (argc > 1) ? atoi(argv[1]) : 1000;
    int cores = get_cores();
    
    log_msg("--- AI Pthread Cramer's Rule Solver ---\n");
    log_msg("System Size (N): %d\n", N);
    log_msg("Detected CPU Cores: %d\n", cores);

    srand(time(NULL));
    Matrix *A = create_matrix(N);
    double *B = (double*)malloc(N * sizeof(double));
    double *solutions = (double*)malloc(N * sizeof(double));

    log_msg("Generating random equations...\n");
    for (int i = 0; i < N; i++) {
        B[i] = ((double)rand() / RAND_MAX) * 20.0 - 10.0;
        for (int j = 0; j < N; j++) A->data[i][j] = ((double)rand() / RAND_MAX) * 20.0 - 10.0;
    }

    log_msg("Computing main determinant...\n");
    double det_A = fast_determinant(A);
    if (fabs(det_A) < 1e-9) {
        log_msg("Error: Singular matrix.\n");
        fclose(log_fp);
        return 1;
    }
    log_msg("Main Determinant: %e\n", det_A);

    pthread_t *threads = malloc(cores * sizeof(pthread_t));
    ThreadArgs *t_args = malloc(cores * sizeof(ThreadArgs));
    int chunk = (N + cores - 1) / cores;

    struct timespec start, end;
    clock_gettime(CLOCK_MONOTONIC, &start);

    for (int p = 0; p < cores; p++) {
        t_args[p].start_col = p * chunk;
        t_args[p].end_col = (p + 1) * chunk;
        if (t_args[p].end_col > N) t_args[p].end_col = N;
        t_args[p].A = A;
        t_args[p].B = B;
        t_args[p].det_A = det_A;
        t_args[p].solutions = solutions;
        t_args[p].thread_id = p;

        if (t_args[p].start_col < N) {
            pthread_create(&threads[p], NULL, worker_routine, &t_args[p]);
        }
    }

    for (int p = 0; p < cores; p++) {
        if (t_args[p].start_col < N) pthread_join(threads[p], NULL);
    }

    clock_gettime(CLOCK_MONOTONIC, &end);
    double time_taken = (end.tv_sec - start.tv_sec) + (end.tv_nsec - start.tv_nsec) / 1e9;

    log_msg("All threads completed.\n");
    log_msg("Total Execution Time: %.4f seconds\n", time_taken);
    log_msg("First 5 Solutions:\n");
    for (int i = 0; i < 5 && i < N; i++) log_msg("  x[%d] = %f\n", i, solutions[i]);

    free(threads); free(t_args); free(solutions); free(B); free_matrix(A);
    fclose(log_fp);
    return 0;
}